### ISSUE TITLE
authnrequest acs not secured

### ISSUE THREAD

**Issue by bradshan** [KentorIT/authservices#240]
after getting everything set up on our mvc app, the authnrequest that is being sent from kentor to out shibb idp is http, rather than https. Is this a bug or could i have set something incorrectly in the config?

Thanks!

**Comment by AndersAbel** [comment]
What API are you using (MVC, Owin, Http Module)?

Do you mean that the AuthnRequest sent from Kentor.AuthServices is sent to an http SSO service on the Idp? Or do you mean that the ACS in the AuthNRequest is not https?

The ACS URL should use the same scheme as used when hitting the ~/AuthServices/SignIn URL. If that one is loaded over https, the ACS URL will be https, otherwise http. Same for metadata. If loaded over https it contains https URLs, otherwise http URLs.

**Comment by bradshan** [comment]
Thank you, no bug, but pointed me to the issue in my config.
