### ISSUE TITLE
Wanting to change return url on AuthServicesController SignIn from querystring

### ISSUE THREAD

**Issue by mip1983** [KentorIT/authservices#271]
Is there a way I can pass a return url i.e via query string to the SignIn on the AuthServices mvc controller? I want it to direct to some where else other than what's configuration. I've tried passing a "ReturnUrl" parameter in the query string, but that hasn't worked.

**Comment by mip1983** [comment]
I'm just doing a little digging into the source code. In IdentityProvider.cs, in 'CreateAuthenticateRequest', it does pick up the returnUrl and put a new 'StoredRequestState' in 'PendingAuthnRequests' with the correct data.

However, when it bounces back from the Idp, part of the logic calls 'GetRequestState' in 'Saml2Response.cs', and this just returns null, not the request state with my return url in it. I don't fully understand the work flow just yet, but that's what I've seen so far...

**Comment by mip1983** [comment]
Further digging, is it possible because there's no 'InResponseTo' in the Saml response from my Idp? It looks like it perhaps only picks up the pending auth request if it's got this key?

**Comment by AndersAbel** [comment]
You're right in your analysis that the return url is preserved in the `PendingAuthnRequest` and retrieved through the `InResponseTo` field in the response.

To support your case if you have discussions with the idp operator/supplier I'd just like to provide a link to the SAML standard. In the [core](https://www.oasis-open.org/committees/download.php/35711/sstc-saml-core-errata-2.0-wd-06-diff.pdf) specification, section 3.2.2 it is explained that `InResponseTo` must be set by the Idp, if it is indeed a response to a previous request:

> InResponseTo [Optional]
A reference to the identifier of the request to which the response corresponds, if any. If the response is not generated in response to a request, or if the ID attribute value of a request cannot be determined (for example, the request is malformed), then this attribute MUST NOT be present.
Otherwise, it MUST be present and its value MUST match the value of the corresponding request's ID attribute.

**Comment by mip1983** [comment]
Thanks Anders. I did ask our Idp operator if they could enable that InResponseTo field. I ended up going another way to solve the issue. Our Idp lets you pass a url encoded 'TargetResource' parameter along with the SAML request, and it returns this as 'RelayState' in the form data along with the SAML token when it posts back to 'Acs', so I can use that as a pass through for the redirect.

I was thinking, if you store the url to redirect to with the PendingAuthnRequest collection, is there a chance that when the Idp redirects back (to 'Acs') that you could end up on a different server in a load balanced web farm, and that redirect url wouldn't be available?

**Comment by albinsunnanbo** [comment]
Yes, there is a problem with load balancing, see https://github.com/KentorIT/authservices/issues/98
