### ISSUE TITLE
Q: working with Identity Server 3

### ISSUE THREAD

**Issue by tonyeung** [KentorIT/authservices#292]
I have a sample repro here: https://github.com/tonyeung/IdSvr3AndKentorAuthServices

I'm not sure what the flow between kentor and idsvr should be?
The idea is to have the user authenticate against saml, then be redirected to idsvr to get a token.
However, I'm not sure if I should be calling the idsvr authentication or kentor authentication, and how the principal/identity is passed.

**Comment by tonyeung** [comment]
I also have an issue open with the IdSvr folks: https://github.com/IdentityServer/IdentityServer3/issues/1734

The project located here: https://github.com/tonyeung/IdSvr3AndKentorAuthServices now reproduces the issue I have. I'm not sure what else to do in order to get this running.

**Comment by AndersAbel** [comment]
The work flow with IdSrv3 is the following.

1. Your application calls IdSrv3. This is required to create an initial request to IdSrv3 so that it knows where to redirect the user back when all authentication is done.
2. On IdSrv3 the user choses SAML authentication (or it is done automatically - I don't know the IdSrv3 options)
3. IdSrv3 invokes AuthServices middleware.
4. AuthServices redirects to SAML Idp for authentication
5. SAML Idp authenticates user and redirects back to AuthServices under IdSrv3.
6. AuthServices handles the incoming SAML assertion on ~/AuthServices/Acs and redirects to IdSrv3
7. IdSrv3 unpacks the identity and creates a token for it and matches it with the request from 1.
8. IdSrv3 redirects back to your application.

There's [a blog post](https://coding.abel.nu/2015/01/saml2-for-thinktecture-identityserver-3-with-kentor-authservices/) on how to use IdSrv3 and AuthServices together too.

**Comment by tonyeung** [comment]
I've tried to reproduce the steps you outlined, but it looks like there's an issue around step 6 or 7.
The reproduction is here: https://github.com/tonyeung/IdSvr3AndKentorAuthServices
The auth base url will need to change to a port that has ssl on it, but otherwise it should be a plug and play.

**Comment by AndersAbel** [comment]
Unfortunately I'm not able to look into this in more detail. If you want commercial support, please mail me. Doing it as a commercial assignment would make my boss way more interested in letting me spend time on this.

**Comment by tonyeung** [comment]
I got it figured out. I was overcomplicating things...

**Comment by AndersAbel** [comment]
If you've figured it out, it would be nice if you could describe the solution so that it's available for others having the same issue.

**Comment by tonyeung** [comment]
I plan on writing something up. As I said, I over complicated things, so the steps to get it working isn't something I can write in a short post.
