### ISSUE TITLE
Support for AuthnContextDecl element in response?

### ISSUE THREAD

**Issue by wjr-** [KentorIT/authservices#297]
Method ProcessAuthenticationStatement in class Saml2SecurityTokenHandler fails if SAML response contains AuthnContextDecl element (Saml2AuthenticationStatement.AuthenticationContext.DeclarationReference is not null). This is a feature in .NET code, see remarks in https://msdn.microsoft.com/en-us/library/system.identitymodel.tokens.saml2authenticationcontext(v=vs.110).aspx

In our solution I just overwrite the value to null. Is there any use for this element? Mapping it to some claim..? I checked SAML documentation but it doesn't really explain the purpose of this element.

**Comment by AndersAbel** [comment]
The `<AuthnContextClassRef>` and `<AuthnContextDeclRef>` elements are used to signal *how* the authentication was done (password, two-factor, smart card, IP address range...).

An SP might chose to only trust an identity from an Idp, if the authentication was done in certain ways. That's why they are present. Until there is such a case where someone needs it, I think it's perfectly fine to just set it to `null` to let it be ignored. If an SP has chosen to trust an Idp, that means that the SP by default trust the Idp to make a proper authentication and that the SP doesn't care about how that is done. If the Idp chose to convey that information it should be safe to ignore it.

In the long run though there should probably be support for it by converting it to a claim. That is probably a non-trivial task though as it is possible to send quite a lot of XML content in those elements.

**Comment by explunit** [comment]
@wjr- what version are you running? There was a change to ignore this element that went into 0.1.13 I think: https://github.com/KentorIT/authservices/pull/249

**Comment by wjr-** [comment]
0.12.1. Have to look into updating. 
Closing this issue.
