### ISSUE TITLE
A very novice question ... 

### ISSUE THREAD

**Issue by whoever123** [KentorIT/authservices#307]
Sorry, just getting started on this and couldn't find much howto 101.  I download the sample and run with the local stub idp.  

It seems SSO only works from SampleApplication to SampleMVC, and only in that direction.  Whatever you do from the MVC app does not impact the other way, login or logout (if logged in separately with different user).  And the SampleOwin does not seem to participate at all.  

Is that how it supposed to be?  Or is there a place in the stub idp that defines this relationship?

Thanks.

**Comment by AndersAbel** [comment]
The stub idp does not support single sign on, it shows the login screen every time it is visited.

The SampleApplication and SampleMVCApplication are accidentally sharing the same auth cookie (which is confusing).

**Comment by saurabh12231978** [comment]
In my case IDP initiated flow I am sending unsolicilated SAMLResponse(with secret key in saml assertion) to SP ACS endpoint(SP supports <Extension>in metadata which shows sso : profile as RequestInitiator) and successfully logged in on SP side and able to access other SP resources. I do see SP is created 2 cookies(ssosession& cookies) Now I am trying to read SP SSO cookies so that I can get access claims and  I can decide wht to show based on claims from SP; How to do that ? pls provide pointers;
