### ISSUE TITLE
Is it possible to provide certificates via code?

### ISSUE THREAD

**Issue by dariusdamalakas** [KentorIT/authservices#335]
We use `KentorAuthServicesSection` to configure IdP in `app.config`. However, we want to load `serviceCertificate` manually via code (we have a custom`ICertificateStore` implementation).  If we omit `serviceCertificate` element, then it fails with a certificate required exception.

Is there any way we can provider certificates via code?

https://github.com/KentorIT/authservices/blob/master/Kentor.AuthServices/Configuration/KentorAuthServicesSection.cs#L326

Thanks

**Comment by explunit** [comment]
Not sure if this helps in your situation, but in my case I am constructing the `SPOptions` purely through code and not using the configuration sections.
```
			var serviceProviderOptions = new SPOptions
			{
				EntityId = new EntityId( myConfig.EntityId ),
				MetadataCacheDuration = TimeSpan.FromSeconds( myConfig.MetadataCacheSeconds ),
				ReturnUrl = new Uri( myConfig.ReturnUrl ),
				ServiceCertificate = myLoadedCert
			};
      // add identity providers etc ...
```
The ServiceCertificate property is marked as get/set. Are you saying that you cannot leave it empty in the config and set it later? What is the exact error message?

**Comment by jeffabailey** [comment]
Hello,

I'm trying to implement code that passes the certificate via code rather than from the .net config as well.

I do not see a public property SPOptions.ServiceCertificate and all other properties that look like candidates for passing the cert via SPOptions don't have a public set method.

What is the current way to do this? I did not see any example of setting up SPOptions with a certificate that isn't defined in the .net config via the <signingCertificate fileName="Kentor.AuthServices.Tests.pfx" /> parameter in the kentor.AuthServices config.

**Comment by AndersAbel** [comment]
@jeffabailey The API has changed since this issue was posted. Use `SPOptions.ServiceCertificates.Add()` to add a certificate from code.

**Comment by jeffabailey** [comment]
@AndersAbel Thanks! I ran into an issue with the code hanging on the Add call when I tried it but it appears to be an issue with my cert specifically so I'll troubleshoot that.
