### ISSUE TITLE
Support for ASP.NET 5.0

### ISSUE THREAD

**Issue by UglyDuckling2k** [KentorIT/authservices#345]
Is it possible to integrate this library within an ASP.NET 5.0 vNext application?

**Comment by AndersAbel** [comment]
Yes, the AuthServices OWIN middleware should be possible to register in an ASP.NET 5 application through a bridging mechanism that allows Katana-compatible middleware in ASP.NET 5.

In the future, I think it would be great to provide a native ASP.NET 5 middleware as well.

There is one huge limitation though: AuthServices only runs on the full .NET Framework and not on CoreCLR. The reason is that neither the SAML2 token support nor XML signature support are yet available on CoreCLR and AuthServices depend heavily on them.

**Comment by AndersAbel** [comment]
I've had feedback from someone trying to use the OWIN middleware with ASP.NET5 and it didn't work. The MW can be registered via an adapter, but they didn't succeed in making the mechanics of sending AuthenticationResponseChallenge via the owin pipeline work. It looks like a new ASP.NET 5 middleware is needed.

**Comment by jsmitman82** [comment]
Will support be coming anytime in the near future? We have an ASP5 MVC6 application that needs to use SAML auth with OKTA, and so far we've had no luck in finding a means of doing this.

**Comment by AndersAbel** [comment]
Reopened #195, so moving discussion there instead.
