### ISSUE TITLE
Error obtaining Certificate Store

### ISSUE THREAD

**Issue by Bryan-Ketley** [KentorIT/authservices#391]
I can load the signing certificate by specifying a filename and reading from that.  I have put your IDPStub certificate into the certificate store and get the following error:

      <signingCertificate storeName ="AuthRoot" storeLocation="CurrentUser" x509FindType="FindBySubjectName" findValue="Kentor.AuthServices.StubIdp" />

Finding cert through FindBySubjectName in CurrentUser:AuthRoot with value Kentor.AuthServices.StubIdp matched 0 certificates. A unique match is required.

Initial Error Stack Follows:
=====================
at Kentor.AuthServices.Configuration.CertificateElement.L
adCertificate()
at Kentor.AuthServices.IdentityProvider.
.ctor(IdentityProviderElement config, ISPOptions spOptions)

at Kentor.AuthServices.Configuration.IdentityProviderCol
lection.RegisterIdentityProviders(IOptions options)
at K
entor.AuthServices.Configuration.Options.get_FromConfigurati

I have also tried by thumbprint and get the same error.  I have tried it quickly in code myself as shown  below and it works:

                    var store = new X509Store(StoreName.CertificateAuthority, StoreLocation.CurrentUser);
                    store.Open(OpenFlags.ReadOnly);
                    try
                    {
                      var certs = store.Certificates.Find(X509FindType.FindByThumbprint, "d3418dbffd46e0e4b8a9bb2f43c4acd47aefbe52", false);

Is there a problem or have I done something silly?
Version 0.14.0.0.
I'm still in Visual Studio 13.  MVC 5.2.3.0

**Comment by explunit** [comment]
I notice that in your code you have store name as `StoreName.CertificateAuthority` (yielding "CertificateAuthority"), but in the config you have `storeName ="AuthRoot"`. Could this be the issue?

Also, which API are you using? e.g. MVC controller or HttpModule?

**Comment by explunit** [comment]
Side note: I think `Trusted People` is the typical store name for Idp certs, but not sure this has any bearing on your problem.

**Comment by magohl** [comment]
I think your problem, if you are trying to get the certificate from "Trusted Root Certification Authorities", is solved by using store-name **"Root"** instead of **"RootAuth"**.

This works on my machine:
```xml
<signingCertificate storeName = "Root" 
                    storeLocation="CurrentUser" 
                    x509FindType="FindBySubjectName" 
                    findValue="Kentor.AuthServices.StubIdp" />
```

Some other tips that might be obvious to some but help others is that normally it’s better to place all certificates used server-side in **LocalMachine** instead of **CurrentUser** as the later most likely won't work in any real world hosting scenarios.

I would recommend placing a certificate for remote-idp-signature-validation in store **AddressBook** (Other People) instead of "Trusted Root Certification Authorities" and point your SP against it.

Depending on how certificate roll-over would be handled one could argue some benefits of using thumbprint (or serial) instead of subject-name as this allows both certificates installed in the store at the same time.

This is how i use the Stub IDP in my configuration:
```xml
      <signingCertificate storeName = "AddressBook"
                                    storeLocation="LocalMachine"
                                    x509FindType="FindByThumbprint"
                                    findValue="d3 41 8d bf fd 46 e0 e4 b8 a9 bb 2f 43 c4 ac d4 7a ef be 52" />
```

**Comment by Bryan-Ketley** [comment]
Thanks people.  I am using MVC and the work pool identity in "Network Services".  From the sounds of it it is working obviously so I will have another try later today.  The pressure is off me on this ATM as It is currently working using the filename.
