### ISSUE TITLE
Load-Balancer potential issues

### ISSUE THREAD

**Issue by crixo** [KentorIT/authservices#406]
As far as I'm aware we had 2 issues in order to use the library on web-farm scenario/beyond a load-balancer:
 -  https://github.com/KentorIT/authservices/issues/340 -> solved

 -  https://github.com/KentorIT/authservices/pull/326 -> on the way to be fixed

Is there any other part of the current master branch that could be potentially not compatible with a web-farm scenario?

**Comment by AndersAbel** [comment]
There are no more issuer that I'm aware of.

With #340 solved, it should be possible to use a load balancer with session affinity enabled.

**Comment by crixo** [comment]
Thanks @AndersAbel for the update.
As far as I read from other thread, a cookie-based fix for the #326 is not in roadmap yet, but it won't be need as long as the load-balancer has the "session affinity enabled".
Just for me knowledge, it seems a quick-win for that issue could be simply rewrite a new version of     PendingAuthnRequests using a different storage instead of the current in-memory dictionary. Am I on right track or I'm missing somenthing here?

**Comment by AndersAbel** [comment]
@crixo A different storage is what was suggested in #326. When looking more into it I unfortunately found out that any kind of server side storage opens up for a CSRF attack on the login flow. To be secure, a cookie must be used so that's what I'm aiming for.

**Comment by crixo** [comment]
@AndersAbel "any kind of server side storage" you mean also the current one indeed? So, if I understood correctly a different storage solves the load-balancer issue, but it remains in place the current "security issue"?

**Comment by AndersAbel** [comment]
@crixo Yes, that is correct. The current storage also has a CSRF issue. That's why I want any time invested in this to be towards a fix that addresses that issue too.

The CSRF issue is not a problem in most cases, as a login sequence is normally not CSRF-protected. Cases where it does matter includes linking several login methods to one account. With large single sign on deploys it might also be a security precaution to CSRF-protect the login sequence to reduce the attack surface for CSRF attacks towards other parts of the application.
