### ISSUE TITLE
Load Metadata from federation config throw exception if the metadata xml only have one entity

### ISSUE THREAD

**Issue by searlin** [KentorIT/authservices#434]
My Idp metadata xml is like below:

`<md:EntityDescriptor xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" ID="idDfmDFapZZg8shlneCkBLQl0hmX8" entityID="entityID">`

So the MetadataLoader will return ExtendedEntityDescriptor instead of ExtendedEntitiesDescriptor, then the exception happens when "return (ExtendedEntitiesDescriptor)Load(metadataLocation)"

I think we need check the return type.

**Comment by albinsunnanbo** [comment]
Hi, can you provide a complete metadata file? (possibly with faked values, but with the structure intact)
Is the metadata following the specification at http://saml.xml.org/saml-specifications ?

**Comment by AndersAbel** [comment]
Looks like you've configured a Federation. It expects an EntitiesDescriptor element. Use an IdentityProvider instead, that is what is to be used for metadata that contgains an EntityDescriptor.

This is not the first time this question shows up, so we should improve the exception message to explain that.

**Comment by searlin** [comment]
@albinsunnanb and @AndersAbel  thanks for your reply.
This is okta Idp metadata https://163sear.okta.com/app/exk4q8ulkgZMRDqud0x7/sso/saml/metadata, I also found that ADFS and NetIQ access manager Idp metadata file are both start with EntityDescriptor instead of EntitiesDescriptor, why not we change the logic to support both EntityDescriptor and EntitiesDescriptor. Below are my code change to support both:

> public static ExtendedEntitiesDescriptor LoadFederation(string metadataLocation)
>         {
>             if (metadataLocation == null)
>             {
>                 throw new ArgumentNullException(nameof(metadataLocation));
>             }
>             MetadataBase metadataBase = Load(metadataLocation);
>             ExtendedEntityDescriptor entity = metadataBase as ExtendedEntityDescriptor;
>             if (entity != null)
>             {
>                 ExtendedEntitiesDescriptor instance = new ExtendedEntitiesDescriptor(entity);
>                 return instance;
>             }
>             return metadataBase as ExtendedEntitiesDescriptor;
>         }

and add  constructor method for ExtendedEntitiesDescriptor:

> public ExtendedEntitiesDescriptor() : base()
>         { }
>         /// <summary>
>         /// Construct for one entity
>         /// </summary>
>         /// <param name="entityDescriptor"></param>
>         public ExtendedEntitiesDescriptor(EntityDescriptor entityDescriptor) : base(new Collection<EntityDescriptor>(new List<EntityDescriptor>() { entityDescriptor }))
>         {
> 
>         }

**Comment by albinsunnanbo** [comment]
Well, SAML2 Metadata specification states:

> 2.3 Root Elements
> A SAML metadata instance describes either a single entity or multiple entities. In the former case, the root element MUST be &lt;EntityDescriptor&gt;. In the latter case, the root element MUST be &lt;EntitiesDescriptor&gt;.

Thus it looks valid with the EntityDescriptor if you have only one IDP in your federation.

Would it be possible to wrap up your code together with some unit tests in a pull request?
See https://github.com/KentorIT/authservices/blob/master/CONTRIBUTING.md on how to best provide a pull request.

You could also create an additional test in FederationTests. Look at Federation_LoadSkolfederationMetadata for an example. You could spoof entityId and location, but keep the general structure. This would serve as a good regression test.

**Comment by AndersAbel** [comment]
There is already perfectly well-working support for metadata that contains a single `<EntityDescriptor>`, through the `IdentityProvider` configuration mechanism. That allows you to set more parameters and mix metadata provided info with configurated info. I won't accept any changes to the current behaviour until you've convinced me about a scenario where the existing mechanism doesn't fulfil your needs.

The only thing I could imagine is a metadata endpoint that currently exposes a single `<EntityDescriptor>` but where the operator of the endpoint has announced that sometime in the future it might change into an `<EntitiesDescriptor>`. I've never heard of anyone experiencing that case. When this issue has been reported before (by mail I think, I can't find an issue for it) it's always been because someone's been doing the configuration wrong.

**Comment by searlin** [comment]
@AndersAbel  you're right, the `IdentityProvider ` is the perfect well-working support for metadata that contains a single` <EntityDescriptor>`, and I understand your point.

I just from my customer's perspective: we built a product and our customer may use third party identity provides to login to our product, the less configuration the better I think.

BTW, none of  the identity providers(ADFS,NetIQ,okta) I tested have single <EntityDescriptor> except your sample provider, so which scenario "Load Metadata from federation" should use?

**Comment by AndersAbel** [comment]
Ok, I see - so you want to have a single configuration place that both can handle the case with an `EntityDescriptor` and `EntitiesDescriptor`.

Is there always a single Idp that is expected? In that case it might be better to change the IdentityProvider configuration to allow for an `EntitiesDescriptor` with a single `EntityDescriptor` in it.

What I want to make sure is that we're not adding flexibility that makes the library harder to use. Right now users are forced to use the correct option of federation or Identityprovider config. With options to automatically translate between them there's more risk that someone is using the wrong config option and gets problem from that.

**Comment by searlin** [comment]
@AndersAbel  ok, I see, you're from all other users' perspective and my case is a little different, I prefer to be more compatible and I can modify the the code for self use, and I support you to  keep current logic, anyway, thank you so much for your information:).

Regarding to your question, I couldn't find a way to change the IdentityProvider configuration to allow for an EntitiesDescriptor

**Comment by AndersAbel** [comment]
I've given some more thought to this and the scenario you describe where a single config option should "just work" makes sense - but not as the default behaviour. I just pushed an update where auto conversion can be done when loading metadata for an IdentityProvider, if enabled in a new Compatibility options section/class.

Please let me know if this works for you.

**Comment by searlin** [comment]
@AndersAbel  sorry that I didn't describe my question clearly, currently,I just want to use the federation config section and leave the identity provider section empty, for example:

>   <kentor.authServices entityId="https://searp:2182/" returnUrl="https://searp:2182/" >
>     <federations>
>       <add metadataLocation="https://federation-qa.basf.com/nidp/saml2/metadata" allowUnsolicitedAuthnResponse="true"/>
>   </kentor.authServices>

but the LoadFederation method in MetadataLoader class can only load EntitiesDescriptor element, and all the metadata xml I tested are all EntityDescriptor element, attachment is the NetIQ identity provider metadata.

**Comment by AndersAbel** [comment]
Why do you want to use the Federation and not the IdentityProvider configuration mechanism?

**Comment by searlin** [comment]
@AndersAbel  as I commented above, I want to let my customer do the least configuration work.

**Comment by AndersAbel** [comment]
I still don't understand why you can't use the IdentityProvider config mechanism? What is the problem with using that?

**Comment by searlin** [comment]
@AndersAbel  when use IdentityProvider config, we need analyze the metadata xml and find the entityid, sign on and sign out url, then put them to the  IdentityProvider config section right? I don't want to let my customer do this, they just need put the metadata url to the federation config.

**Comment by searlin** [comment]
By the way,may I ask in your perspective which scenario should I use Federation config?

**Comment by AndersAbel** [comment]
If you use the IdentityProvider config you're right in that the EntityId must still be configured, but that is something that has been suggested as an improvement (#305). The sign in and out url are not needed to be configured if you load metadata. Those properties are only needed if you configure an Idp without using metadata. So what you really would need is #305 to be implemented?

Federation config is used if you have a dynamic list of identity providers. See https://fed.skolfederation.se/prod/md/skolfederation-3_0.xml for example of such a metadata file.

**Comment by searlin** [comment]
@AndersAbel  yes, you're exactly right, if metadata xml is provided, I don't need want customer to type anything else.

And thank you for explain the purpose of Federation config, I understand it now.

**Comment by AaronLS** [comment]
Thanks for considering this change.

I ran into the same issue.  Valid federation metadata throwing an exception due to single element.  It is valid metadata and the metadataLocation is intended to support metadata.  I don't see any reason I shouldn't expect this to work.  There's nothing about a Federation endpoint that implies it should only represent multiple descriptors.  They explicitly allow a single element as the root in the standard because it's perfectly reasonable to want to leverage that metadata for configuration.

It's really nice for getting things working quickly and not have to second guess myself on whether I got multiple configuration values correct.  Then I can focus on other pieces of the authentication process and when there are issues, I don't have to consider whether my IdentityProvider configuration is to blame.

If it doesn't support valid metadata for the metadataLocation, then isn't that a bug?  Yes you could accomplish the same thing using IdentityProvider, but that's a work around.  If the fact that I could do it another way means it's not a bug, then the same argument could be made for metadata support all together.  You could even argue against config file support at all, and say that you must just code configuration programmatically.  

Why repeat configuration in IdentityProvider that's already present in Metadata and risk fat fingering it and having to go back and forth?  My favorite quote is "I object to doing things computers can do?" - Olin Shivers

**Comment by AaronLS** [comment]
It's also just plain confusing.  As soon as I encountered it, I assumed either the metadata was to blame, or I was to blame, and spent a bunch of time troubleshooting, only to eventually look through the source and see it is making an **invalid assumption** about the structure of the metadata file.

**Comment by AndersAbel** [comment]
@AaronLS Can you please describe exactly what change you would like to see? Is it #305 that you want implemented?

The AuthServices configuration is built around two concept: Either you configure a single Identity Provider, or you use a dynamically loaded list of multiple Idps such as when connecting to the InCommon federation. In that case the configuration is done more in a template based manner for settings like AllowUnsolicitedAuthnResponse. Also, if an Idp is not available it will silently be ignored. I don't think that is what people expect if they configure against a single Idp. 

Since som products, such as ADFS use the name "Federation" even for a single Idp the naming is confusing.

But I still think that having the distinction between "I'm configuring a single Idp or this list of Idps that I know" and "I want to trust a bunch of listed Idps that get changed dynamically" is quite different. In the latter case a Discovery Service is typically needed too.

So, @AaronLS please tell me exactly what change you would like to see and why.

**Comment by AaronLS** [comment]
@AndersAbel 
I would recommend support a single EntityDescriptor:

```
 <federations>
      <add metadataLocation="http://someidp.com/Federation" allowUnsolicitedAuthnResponse="true" />   
</federations>
```

When I say, "Trust this metadata location", to me, it doesn't matter whether it's a single vs list. Regardless of whether there's one or more than one, just trust whatever is defined by the metadata.

I've seen and written plenty of C# functions that take a List<T>, but are also just as useful when passing a list that contains only one item.  I don't go throwing exceptions that say "You passed a List<int> of Count == 1.  A List should contain more than one item."

It's really confusing to setup the first time with seemingly valid metadata, and have the library choke on it. I started second guessing myself and eyeballing the metadata or thinking I did something wrong.

**Comment by AndersAbel** [comment]
No, you don't get exceptions saying "You passed a list of Count == 1", because that is fine. And AuthServices is fine with loading federation metadata with a root `<EntitiesDescriptor>` containing only one `<EntityDescriptor>`. If you have `MyMethod(List<int> l)` you will however get compiler errors if you try to call it with `MyMethod(1)`.

AuthServices is meant to have two different configuration mechanisms. One for fixed, known Identity Providers and one for a dynamically loaded list containing multiple Identity Providers. They are not only different in the configuration but also behave differently if there are issues with the metadata. Using a federation for a single identity provider is a bad idea. If a federation configuration is used and the root is `<EntityDescriptor>` the current exception message is:

> Tried to load metadata for a Federation, which should be an <EntitiesDescriptor> containing one or more <EntityDescriptor> elements, but found an <EntityDescriptor>. To load that metadata you should use the IdentityProvider configuration and not a Federation.

I thought that would be enough to direct anyone to change the configuration. Did you get that exception message? Can it be rephrased to make it more obvious that the configuration need to be changed? Someone using the wrong config method shouldn't have to go reading the source as you did - it should be apparent what need to be changed.

**Comment by AaronLS** [comment]
@AndersAbel I was getting some sort of cast exception, but retested this case and have recently updated to newest version, and it is giving a very informative error.

It would seem like you'd want the same dynamic behavior, single or not, but it sounds like there are nuances that I don't understand, so I'll take your word. Thanks :)
