### ISSUE TITLE
Question about ExpandReturnUrl and PublicOrigin

### ISSUE THREAD

**Issue by explunit** [KentorIT/authservices#474]
What is the purpose of expanding ReturnUrl during the sign-in phase (`SignInCommand.ExpandReturnUrl`)?
https://github.com/KentorIT/authservices/blob/master/Kentor.AuthServices/WebSSO/SignInCommand.cs#L119

And if it does need to be expanded, shouldn't this use `PublicOrigin`?

**Comment by AndersAbel** [comment]
The ReturnUrl expansions has caused me a lot of headache. They are probably still not entirely correct.

The scenario I'm trying to cover is when using the Owin middleware, the signin can be initiated from any page/location in the web site. When doing the redirect, that will always be done from ~/AuthServices/Acs. If a relative URL is given as ReturnUrl, I'm trying to cover for the final redirect being done from a different location.

An example:
1. Sign in is initiated at `/SomePath/Welcome` with ReturnUrl `LoggedIn`, which refers to `/SomePath/LoggedIn`.
2. AuthServices redirects to Idp.
3. AuthServices receives response at `/AuthServices/Acs`.
4. AuthServices redirects. If the ReturnUrl `LoggedIn` is used directly, the browser will interpret that as `/AuthServices/LoggedIn` and not `/SomePath/LoggedIn`. That's why I'm expanding.

But thinking of it relative return urls probably never exists. And the expansion is error prone, so maybe it should be completely scrapped? I mean it's simple for the user of the library to use relative paths from the start `/SomePath/LoggedIn`.

**Comment by explunit** [comment]
I've assumed that since we default to looking at the `ReturnUrl` querystring parameter just like the old forms auth, that we should default to the same kind of behavior, which is to reject non-local Urls and not expand them.

**Comment by AndersAbel** [comment]
It's probably a better idea. I can check (but not now) how the Google Auth Owin middleware works, it has the same issue with a post-back to a specific path.

**Comment by explunit** [comment]
#476
