### ISSUE TITLE
ID3061: The given element AudienceRestriction is empty.

### ISSUE THREAD

**Issue by piermorosini** [KentorIT/authservices#620]
Hi,
I have this error.

ID3061: The given element ('AudienceRestriction','urn:oasis:names:tc:SAML:2.0:assertion') is empty.

Thanks
Pierluigi

**Comment by explunit** [comment]
The best solution is for your identity provider to set this value in the assertions they provide to you, since it protects against certain kind of attack.

However, if you want to turn off audience validation then you can do something like this:

`mySPOptions.SystemIdentityModelIdentityConfiguration.AudienceRestriction.AudienceMode = AudienceUriMode.Never;`

**Comment by piermorosini** [comment]
Hi,
i changed json in provider and all wors fine now.

Thank you very much.
Pierluigi
