### ISSUE TITLE
BootstrapContext not being saved even when explicitly set to do so via SPOptions.SystemIdentityModelIdentityConfiguration.SaveBootstrapContext

### ISSUE THREAD

**Issue by jimitndiaye** [KentorIT/authservices#674]
I'm using a code-based OWIN setup (no config) and I am explicitly setting the relevant setting to true and yet at runtime the ClaimsIdentity's BootstrapContext is consistently null.

**Comment by AndersAbel** [comment]
Implement the `AcsCommandResultCreated` notification and check the supplied `CommandResult.Principal` parameter. It should contain the BoostrapContext. However, it is as far as I know not preserved when the principal is serialied by the cookie middleware. So if you check in subsequent requests the BootstrapContext will probably be null.

**Comment by jimitndiaye** [comment]
Is there anyway of accessing it outside of AcsCommandResultCreated?

**Comment by AndersAbel** [comment]
Yes, it will be part of the identity in the `AuthenticationResponseGrant`, which can be accessed by middleware registered before AuthServices in the pipeline. But you need to get it and preserve it in the request to `~/AuthServices/Acs` because in subsequent requests, the identity comes from the serialized data that the cookie middleware handles. And the cookie middleware doesn't support `BootstrapContext`.
