### ISSUE TITLE
Saml2PostBinding.UnBind is always TrustLevel.None.

### ISSUE THREAD

**Issue by leotohill** [KentorIT/authservices#678]
Why does Saml2PostBinding.UnBind only support TrustLevel.None?  Is this just unfinished work?  It seems odd that Logout() does a signature check but AcsCommand does not.  

I could be totally missing something, but without signature verification on the samlResponse, this can’t be ready for production, can it?

**Comment by leotohill** [comment]
I see now that validation is lazy-deferred until GetClaims(), so I'm happy to see that the signature is verified.

**Comment by AndersAbel** [comment]
Thanks for taking time to do a thorough investigation. The design idea behind TrustLevel is to attach a marker to a message wheter it has already been verified. The bindings differ on where the verification takes place. For Artifact, the verification can be on the https level with a normal server certificate from the idp. For Redirect, the signature is handled by the binding and not part of the message. Then the actual message (and any included assertions) wouldn't carry any signatures. So for the POST binding, the binding is correct in hard coding `TrustLevel.None`, because when using the post binding the signature is part of the message and is verified later.

For future reference, if you have any security issues please don't post them in public but disclose them privately by e-mail.
