### ISSUE TITLE
Final application entry point without Redirect?

### ISSUE THREAD

**Issue by leotohill** [KentorIT/authservices#690]
In the example application, after the response to the AuthnRequest is successfully processed, a redirect is used to finally invoke the service provider's function.   Is there a way (currently or envisioned) to invoke the application's entry point directly, without resorting to a redirect?  Possibly by specifying a callback function?

**Comment by AndersAbel** [comment]
Yes, you can use AcsCommandResultCreated notification to hook in your own processing right away. But it is a bad idea, because the user would end up seeing the ~/AuthServices/Acs path as the URL. If the user hits reload, the Acs command is invoked again which will not work.

Doing a redirect follows the recommended [POST-Redirect-GET](https://en.wikipedia.org/wiki/Post/Redirect/Get) pattern.
