### ISSUE TITLE
Is there a sample using multiple IdPs?

### ISSUE THREAD

**Issue by BjoernBeeli** [KentorIT/authservices#724]
Based on the SampleOwinApplication I want to configure more than one IdP, so that it show for each IdP on the login page the authorization button.

Is there any sample code (based on SampleOwinApplication) where multiple identity providers are used?
* setup the IdP's in Startup.Auth.cs with config details in web.config
* allow to list different IdP's on the login page
* type of IdP's: SAML2p one and also others like Google-IdP
* integrate ClaimsAuthenticationManager sample in that scenario for claims transformation
* it's not clear how to use the discovery service and the federation metadata

I was not able to define multiple identity providers in web.config, so that they are listed on the login page!
Here is the web.config part:
```
<identityProviders>
    <add entityId="http://stubidp.kentor.se/Metadata" 
        signOnUrl="http://stubidp.kentor.se" 
        allowUnsolicitedAuthnResponse="true" binding="HttpRedirect">
    <signingCertificate fileName="~/App_Data/Kentor.AuthServices.StubIdp.cer" />
    </add>
    <add entityId="http://localhost:8080/simplesaml/saml2/idp/metadata.php" 
        signOnUrl="http://localhost:8080/simplesaml/saml2/idp/SSOService.php" 
        logoutUrl="http://localhost:8080/simplesaml/saml2/idp/SingleLogoutService.php" 
        allowUnsolicitedAuthnResponse="true" binding="HttpRedirect">
        <signingCertificate fileName="~/App_Data/SimpleSAML.IdP.W104.cer" />
    </add>
</identityProviders>
```

**Comment by AndersAbel** [comment]
The default login page lists *authentication schemes*. Each *middleware* has an own scheme. The other owin/katana middlewares such as for open id connect only support a single Idp per instance, so listing middleware instances makes sense. AuthServices is a bit special in that it supports multiple Idps in *single middleware instance*.

A discovery service is a SAML2 extension standard that lets you have an intermediate step where you select what Idp to use. Federation is a somewhat advanced concept where you have a large list of Idps you trust (see https://www.incommon.org/federation/ for an example).

If you want multiple Idps on the login page you need to modify it so that it lists the known Idps for AuthServices. Then you need to put the selected idp in the authentication challenge (see owin docs for details). Or you can have one AuthServices middleware instance per idp.
