### ISSUE TITLE
deny users="?" endless redirect

### ISSUE THREAD

**Issue by Mishu** [KentorIT/authservices#734]
Hello, 
If you have an mvc application that has this config: 
`<authorization>
      <deny users="?" />
    </authorization>` 
Then you get redirected to the stubIdp on and on...
To verify just add that element in the SampleMvcApplication and see the behaviour...

Thanks,
Mishu

**Comment by AndersAbel** [comment]
This is by design due to how web.config based authorization works.

The web.config based authorization happens before the MVC controller is run. If you use web.config based authorization rules you need to allow anonymous access to ~/AuthServices. And using web.config based authorization rules is legacy, in an MVC application you should use attributes on the controllers/actions. If you want all controllers/actions except those decorated with `[AllowAnonymous]` to require login add the following global filter in `RegisterGlobalFilters()`:

`filters.Add(new AuthorizeAttribute());`

Please see https://weblogs.asp.net/jongalloway/asp-net-mvc-authentication-global-authentication-and-allow-anonymous for more in depth explanation.

**Comment by Mishu** [comment]
Thanks for the answer. Yeah it's about an old legacy app.
